### ISSUE TITLE
Push the docs into the monorepo

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/docs#16]
Once done:
- [ ] Remove the Github Action on the monorepo that copies the CHANGELOG.md to the `docs` subfolder

**Comment by mieubrisse** [comment]
Pari in [his user experience session](https://www.notion.so/kurtosistech/2022-12-20-Pari-ETH-User-Experience-Call-e911f2a9a3534050b20d6c879901127c) mentioned friction about the docs not being in with the monorepo. I think we should just move these even while the monorepo is private.

**Comment by victorcolombo** [comment]
Done by https://github.com/kurtosis-tech/kurtosis/pull/833
